# Generated by Django 2.1.8 on 2019-05-07 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='last_version_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
