# Generated by Django 2.1.8 on 2019-11-11 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_management', '0002_library_last_version_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='last_version_date',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
