# Generated by Django 2.1.8 on 2019-11-11 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_management', '0003_set_last_version_field_non_editable'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='repo_type',
            field=models.CharField(choices=[('GITHUB', 'Github'), ('GITLAB', 'Gitlab')], default='GITHUB', max_length=10),
        ),
    ]
