# Generated by Django 2.1 on 2018-08-27 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_management', '0005_auto_20180827_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='projectlibrary',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
