# Generated by Django 2.1 on 2018-08-31 08:49

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('projects_management', '0009_auto_20180829_1632'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='library',
            table='projects_management_library',
        ),
        migrations.AlterModelTable(
            name='project',
            table='projects_management_project',
        ),
        migrations.AlterModelTable(
            name='projectlibrary',
            table='projects_management_projectlibrary',
        ),
    ]
