# Generated by Django 2.1 on 2018-08-27 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectsmanagement', '0003_auto_20180827_0811'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectlibrary',
            options={'ordering': ['project'], 'verbose_name': 'Library of project', 'verbose_name_plural': 'Libraries of projects'},
        ),
    ]
