# Generated by Django 2.1 on 2018-08-27 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectsmanagement', '0004_auto_20180827_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='library',
            name='version_check_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
