# Generated by Django 2.1 on 2018-08-28 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectsmanagement', '0007_auto_20180828_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectlibrary',
            name='check_mayor_version_update',
            field=models.BooleanField(default=True, verbose_name='Check Mayor Update'),
        ),
        migrations.AlterField(
            model_name='projectlibrary',
            name='check_minor_version_update',
            field=models.BooleanField(default=True, verbose_name='Check Mayor Update'),
        ),
        migrations.AlterField(
            model_name='projectlibrary',
            name='check_patch_version_update',
            field=models.BooleanField(default=False, verbose_name='Check Minor Update'),
        ),
    ]
