# Generated by Django 2.1 on 2018-08-24 14:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('repo_url', models.URLField()),
                ('last_version', models.CharField(blank=True, max_length=20)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('version_check_date', models.DateTimeField(editable=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('repo_url', models.URLField(unique=True)),
                ('environment', models.CharField(choices=[('DEV', 'Development'), ('STAGING', 'Staging'), ('RELEASE', 'Release'), ('PRO', 'Production')], max_length=20)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectLibrary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_version', models.CharField(max_length=20)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectsmanagement.Library')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectsmanagement.Project')),
            ],
        ),
    ]
